### ISSUE TITLE
Runtime exception

### ISSUE THREAD

**Issue by Maxopoly** [shadowjay1/AqPvP#1]
[19:40:40 ERROR]: Could not pass event PlayerInteractEvent to AqPvP v0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:759) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:52) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1) [?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar
:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
14) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
53) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(Cra
ftLivingEntity.java:83) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at me.aqlow.spigot.pvp.MagicManager.reducePlayerResource(MagicManager.ja
va:201) ~[?:?]
        at me.aqlow.spigot.pvp.MagicManager.onPlayerInteract(MagicManager.java:1
20) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 17 more

**Comment by shadowjay1** [comment]
Fixed.
