### ISSUE TITLE
Another stack

### ISSUE THREAD

**Issue by Maxopoly** [shadowjay1/AqPvP#2]
[19:47:40 ERROR]: Could not pass event EntityDamageByEntityEvent to AqPvP v0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDama
geEvent(CraftEventFactory.java:552) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDa
mageEvent(CraftEventFactory.java:465) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEn
tityDamageEvent(CraftEventFactory.java:584) [spigot.jar:git-Spigot-d97e08b-880a5
32]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [
spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spi
got.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.j
ava:733) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.jav
a:800) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.j
ava:496) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001ot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355)
[spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.
jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.
jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spi
got.jar:git-Spigot-d97e08b-880a532]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1
.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Sp
igot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [sp
igot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [sp
igot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [sp
igot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivin
gEntity.java:83) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at me.aqlow.spigot.pvp.MagicManager.reducePlayerResource(MagicManager.java:201)
 ~[?:?]
        at me.aqlow.spigot.pvp.MagicManager.onPlayerDamageEntity(MagicManager.java:170)
 ~[?:?]
        at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl
.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
 ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 26 more

**Comment by shadowjay1** [comment]
Same bug as #1. Fixed.
